/*
  Warnings:

  - You are about to drop the column `IDRATE` on the `galeryrate` table. All the data in the column will be lost.
  - Added the required column `RATE_UUIDAPP` to the `galeryrate` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE "galeryrate" DROP CONSTRAINT "galeryrate_IDRATE_fkey";

-- AlterTable
ALTER TABLE "galeryrate" DROP COLUMN "IDRATE",
ADD COLUMN     "RATE_UUIDAPP" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "rate" ADD COLUMN     "FILIAL_WEB" TEXT,
ALTER COLUMN "STATUS" SET DEFAULT 'EM ANDAMENTO',
ALTER COLUMN "CANAL" DROP NOT NULL,
ALTER COLUMN "INDICATOR" DROP NOT NULL,
ALTER COLUMN "MODALITY" DROP NOT NULL,
ALTER COLUMN "OBSALL" DROP NOT NULL,
ALTER COLUMN "OBSREASON" DROP NOT NULL,
ALTER COLUMN "REASON" DROP NOT NULL,
ALTER COLUMN "RESSED" DROP NOT NULL,
ALTER COLUMN "STOKE" DROP NOT NULL,
ALTER COLUMN "TAXA" DROP NOT NULL,
ALTER COLUMN "VALIDITY" DROP NOT NULL,
ALTER COLUMN "VALUE1YEAR" DROP NOT NULL,
ALTER COLUMN "VALUE2YEAR" DROP NOT NULL,
ALTER COLUMN "VALUE3YEAR" DROP NOT NULL,
ALTER COLUMN "VALUE4YEAR" DROP NOT NULL,
ALTER COLUMN "VALUEBY" DROP NOT NULL,
ALTER COLUMN "VALUENEG" DROP NOT NULL,
ALTER COLUMN "VALUERATE" DROP NOT NULL,
ALTER COLUMN "VALUESUG" DROP NOT NULL,
ALTER COLUMN "VALUEVIEW" DROP NOT NULL,
ALTER COLUMN "WHO" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "galeryrate" ADD CONSTRAINT "galeryrate_RATE_UUIDAPP_fkey" FOREIGN KEY ("RATE_UUIDAPP") REFERENCES "rate"("UUIDAPP") ON DELETE CASCADE ON UPDATE CASCADE;
