import Joi from "joi";

const updateRate = Joi.object({
  UUIDAPP: Joi.string().allow("").optional(),
  IDVERSIONCHECKIN: Joi.string().optional(),
  RESULT: Joi.string().optional(),
  STATUS: Joi.string().max(250).optional(),
  MESSAGE: Joi.string().allow("").optional(),
  TYPE: Joi.string().max(250).optional(),
  MARK: Joi.string().max(250).optional(),
  MODEL: Joi.string().max(250).optional(),
  CHASSI: Joi.string().max(250).optional(),
  VALUE: Joi.string().max(250).optional(),
  CODVEND: Joi.string().max(250).optional(),
  FILIAL: Joi.string().max(250).optional(),
  NAMEVEND: Joi.string().max(250).optional(),
  EMAILVEND: Joi.string().email().max(250).optional(),
  CODCLI: Joi.string().max(250).optional(),
  LJCLI: Joi.string().max(250).optional(),
  CODPROS: Joi.string().max(250).optional(),
  LJPROS: Joi.string().max(250).optional(),
  NAMECLI: Joi.string().max(250).optional(),
  ADDRESSCLI: Joi.string().max(250).optional(),
  PHONECLI: Joi.string().max(250).optional(),
  EMAILCLI: Joi.string().email().max(250).optional(),
  DATE: Joi.string().max(250).optional(),
  VALUE1YEAR: Joi.string().max(250).optional(),
  VALUE2YEAR: Joi.string().max(250).optional(),
  VALUE3YEAR: Joi.string().max(250).optional(),
  VALUE4YEAR: Joi.string().max(250).optional(),
  TAXA: Joi.string().max(250).optional(),
  VALUEVIEW: Joi.string().max(250).optional(),
  VALUERATE: Joi.string().max(250).optional(),
  VALIDITY: Joi.string().max(250).optional(),
  VALUESUG: Joi.string().max(250).optional(),
  FILIAL_WEB: Joi.string().max(250).optional(),
  CANAL: Joi.string().max(250).optional(),
  RESSED: Joi.boolean().optional(),
  MODALITY: Joi.string().max(250).optional(),
  VALUEBY: Joi.string().max(250).optional(),
  VALUENEG: Joi.string().max(250).optional(),
  STOKE: Joi.boolean().optional(),
  REASON: Joi.boolean().optional(),
  OBSREASON: Joi.string().max(250).optional(),
  INDICATOR: Joi.boolean().optional(),
  WHO: Joi.string().max(250).optional(),
  OBSALL: Joi.string().optional(),
});

export default updateRate;
