-- CreateTable
CREATE TABLE "user" (
    "ID" UUID NOT NULL,
    "ROLE" TEXT NOT NULL DEFAULT 'USER',
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "checkin" (
    "ID" UUID NOT NULL,
    "NAME" TEXT NOT NULL,
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "checkin_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "schema" (
    "ID" UUID NOT NULL,
    "TITLE" TEXT NOT NULL,
    "IDCHECKIN" UUID NOT NULL,
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "schema_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "model" (
    "ID" UUID NOT NULL,
    "NAME" TEXT NOT NULL,
    "TITLE" TEXT NOT NULL,
    "QUESTION" TEXT NOT NULL,
    "IDSCHEMA" UUID NOT NULL,
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "model_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "input" (
    "ID" UUID NOT NULL,
    "TYPE" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "LABEL" TEXT NOT NULL,
    "PLACEHOLDER" TEXT,
    "VALUE" TEXT NOT NULL DEFAULT '',
    "MIN" INTEGER,
    "MAX" INTEGER,
    "REQUIRED" BOOLEAN NOT NULL DEFAULT false,
    "MULTIPLE" BOOLEAN NOT NULL DEFAULT false,
    "BONDTYPE" TEXT NOT NULL DEFAULT '',
    "IDMODEL" UUID NOT NULL,
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "input_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "enum" (
    "ID" UUID NOT NULL,
    "NAME" TEXT NOT NULL,
    "TITLE" TEXT NOT NULL,
    "IDINPUT" UUID NOT NULL,
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "enum_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "version_checkin" (
    "ID" UUID NOT NULL,
    "IDCHECKIN" UUID NOT NULL,
    "NAME" TEXT NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "JSON_CHECKIN" TEXT NOT NULL,
    "OBJECT_CHECKIN" TEXT NOT NULL,
    "VIDEO" BOOLEAN NOT NULL DEFAULT false,
    "PHOTO" BOOLEAN NOT NULL DEFAULT false,
    "ATIVE" BOOLEAN NOT NULL DEFAULT true,
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "version_checkin_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "rate" (
    "ID" SERIAL NOT NULL,
    "UUID" TEXT NOT NULL,
    "IDVERSIONCHECKIN" UUID NOT NULL,
    "TYPE" TEXT NOT NULL,
    "MARK" TEXT NOT NULL,
    "MODEL" TEXT NOT NULL,
    "CHASSI" TEXT NOT NULL,
    "VALUE" TEXT NOT NULL,
    "RESULT" TEXT NOT NULL,
    "STATUS" TEXT NOT NULL,
    "CODVEND" TEXT NOT NULL,
    "EMAILVEND" TEXT NOT NULL,
    "CODCLI" TEXT NOT NULL,
    "LJCLI" TEXT NOT NULL,
    "CODPROS" TEXT NOT NULL,
    "LJPROS" TEXT NOT NULL,
    "NAMECLI" TEXT NOT NULL,
    "DATE" TEXT NOT NULL,
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "rate_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "markwheels" (
    "ID" SERIAL NOT NULL,
    "UUID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "markwheels_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "user_EMAIL_key" ON "user"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "rate_UUID_key" ON "rate"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "markwheels_UUID_key" ON "markwheels"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "markwheels_NAME_key" ON "markwheels"("NAME");

-- AddForeignKey
ALTER TABLE "schema" ADD CONSTRAINT "schema_IDCHECKIN_fkey" FOREIGN KEY ("IDCHECKIN") REFERENCES "checkin"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "model" ADD CONSTRAINT "model_IDSCHEMA_fkey" FOREIGN KEY ("IDSCHEMA") REFERENCES "schema"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "input" ADD CONSTRAINT "input_IDMODEL_fkey" FOREIGN KEY ("IDMODEL") REFERENCES "model"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "enum" ADD CONSTRAINT "enum_IDINPUT_fkey" FOREIGN KEY ("IDINPUT") REFERENCES "input"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rate" ADD CONSTRAINT "rate_IDVERSIONCHECKIN_fkey" FOREIGN KEY ("IDVERSIONCHECKIN") REFERENCES "version_checkin"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
